# Generated by Django 4.0.2 on 2023-09-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover',
            field=models.ImageField(blank=True, upload_to='product/product_covers/', verbose_name='Product Cover'),
        ),
    ]
