# Generated by Django 4.0.2 on 2023-09-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_product_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/image_and_cover/', verbose_name='Product Image'),
        ),
    ]
